<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ page session="false" %>
<html>
<head>
	<title>Home</title>
</head>
<body>
<h1>
	Hello world!  
</h1>

<P>  The time on the server is ${serverTime}. </P>
<p>
CREATE TABLE TB_BOARD(
	IDX INT PRIMARY KEY AUTO_INCREMENT,
	PARENT_IDX INT,
	TITLE VARCHAR(100) NOT NULL,
	CONTENTS VARCHAR(400) NOT NULL,
	HIT_CNT INT NOT NULL,
	DEL_GB VARCHAR(1) DEFAULT 'N' NOT NULL,
	CREA_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CREA_ID VARCHAR(30)
);

CREATE TABLE TB_FILE(
	IDX INT PRIMARY KEY AUTO_INCREMENT,
	BOARD_IDX INT NOT NULL,
	ORIGINAL_FILE_NAME VARCHAR(260) NOT NULL,
	STORED_FILE_NAME VARCHAR(36) NOT NULL,
	FILE_SIZE INT,
	CREA_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CREA_ID VARCHAR(30) NOT NULL,
	DEL_GB VARCHAR(1) NOT NULL DEFAULT 'N'
);
</p>
</body>
</html>
